version: '3.5'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    restart: unless-stopped
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
#      - /odoo_ar/netdata:/usr/lib/netdata/conf.d/:ro
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
#      - /etc/passwd:/host/etc/passwd:ro
#      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - PGID=999  
  # obtener el PGID
  # grep docker /etc/group | cut -d ':' -f 3

volumes:
  netdatalib:
  netdatacache: