# Configuracion para RCLONE hay que crear el rclone.conf para eso ver el video del pelado.
# https://www.youtube.com/watch?v=mnDYJ2ZpdxU&t=181s
# https://github.com/Mumie-hub/
#
# Crear archivo de configuracion
# sd run -it -v ~/.config/rclone:/config/rclone rclone/rclone config
#

version: '2'
services:
  rclone-mount:
    container_name: rclone
    image: mumiehub/rclone-mount
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/jobiols/.config/rclone:/config
      # - /mnt/gdrive:/mnt/mediaefs:shared
      - /odoo_ar/odoo-11.0e/jeo/backup_dir:/mnt/mediaefs:shared
    logging:
      options:
        max-size: 1g
    devices:
      - /dev/fuse
    environment: 
      - 'RemotePath=gdrive:'
      - 'MountCommands=--allow-other --allow-non-empty --buffer-size 256M --vfs-cache-mode writes'
      - 'ConfigName=rclone.conf'
