version: '3.5'
services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"    
    read_only: true
    tmpfs: 
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - /mnt:/mnt
#      - /mnt2:/mnt2:z
    command: '-s "Odoo Backup 1;/mnt;yes;yes;yes;;;;Archivos de backup diarios maximo 30 dias." -p'

networks:
  default:
