# Compose file odoo test13 con letsencrypt
# Version 2020-07-17

version: '3.5'

services:

  postgres:
    image: postgres:10.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - postgresql:/var/lib/postgresql/data

  test13:
    image: jobiols/odoo-jeo:13.0
    container_name: test13
    restart: always
    volumes:
      - /odoo_ar/odoo-13.0/test13/config:/opt/odoo/etc/
      - /odoo_ar/odoo-13.0/test13/data_dir:/opt/odoo/data
      - /odoo_ar/odoo-13.0/test13/log:/var/log/odoo
      - /odoo_ar/odoo-13.0/test13/sources:/opt/odoo/custom-addons
      - /odoo_ar/odoo-13.0/test13/backup_dir:/var/odoo/backups/
    links:
      - postgres:db
    environment:
      - ODOO_CONF=/dev/null

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /odoo_ar/nginx/conf/:/etc/nginx/conf.d:ro
      - /odoo_ar/nginx/log:/var/log/nginx/
    links:
      - test13
    environment:
      - VIRTUAL_HOST=staging.jeosoft.com.ar
      - LETSENCRYPT_HOST=staging.jeosoft.com.ar
      - LETSENCRYPT_EMAIL=jorge.obiols@gmail.com

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  certs:
  html:
  vhostd:
  postgresql:
