#run with $VIRTUALIZATION=()

version: "3"

services:
  netdata:
    image: netdata/netdata
    hostname: odoo.makeoverlab.com.ar
    restart: unless-stopped
    ports: 
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
#    environment:
#      - VIRTUALIZATION=${VIRTUALIZATION}

volumes:
  netdatalib:
  netdatacache:
